### ISSUE TITLE
Library no longer works with Kafka < 0.11

### ISSUE THREAD

**Issue by aseigneurin** [manub/scalatest-embedded-kafka#87]
A recent commit replaces configuration properties with a reference to constants. Some of these constants only exist in Kafka 0.11, thus breaking at execution time when running with Kafka < 0.11.

See https://github.com/manub/scalatest-embedded-kafka/commit/868449d530030607627400e274270056d55d1057#diff-94790827da36cdd54fa6cb75094a4f84R471

```
*** RUN ABORTED ***
  java.lang.NoSuchMethodError: kafka.server.KafkaConfig$.TransactionsTopicReplicationFactorProp()Ljava/lang/String;
  at net.manub.embeddedkafka.EmbeddedKafkaSupport$class.startKafka(EmbeddedKafka.scala:542)
```

**Comment by manub** [comment]
Thanks - this is a `SNAPSHOT` anyway. I guess we could inline the values as those will simply be ignored for earlier versions. Will do that.
