### ISSUE TITLE
anomaly with KafkaConfig class in maven and sbt artefact vXXX_2.11 version 0.10.0 

### ISSUE THREAD

**Issue by sameergarg** [manub/scalatest-embedded-kafka#56]
## In sbt

class KafkaConfig(val props: java.util.Map[_, _], doLog: Boolean) extends AbstractConfig(KafkaConfig.configDef, props, doLog) {

def this(props: java.util.Map[_, _]) = this(props, true)

## In maven
-----------
class KafkaConfig private (val props: VerifiableProperties) extends ZKConfig(props) {

  def this(originalProps: Properties) {
    this(new VerifiableProperties(originalProps))
    props.verify()
  }

## Error using maven
---------
Causes test to abort giving NoSuchMethodError

An exception or error caused a run to abort: kafka.server.KafkaConfig.<init>(Ljava/util/Map;)V 
java.lang.NoSuchMethodError: kafka.server.KafkaConfig.<init>(Ljava/util/Map;)V
	at net.manub.embeddedkafka.EmbeddedKafkaSupport$class.startKafka(EmbeddedKafka.scala:293)
	at net.manub.embeddedkafka.EmbeddedKafka$.startKafka(EmbeddedKafka.scala:36)
	at net.manub.embeddedkafka.EmbeddedKafka$.start(EmbeddedKafka.scala:48)

## My spec
```
class KafkaConnectorSpec extends WordSpec with Matchers with EmbeddedKafka {

  implicit val config = EmbeddedKafkaConfig(kafkaPort=7000, zooKeeperPort = 7001)

  "embedded kafka" when {
    "using internal library" should {
      "produce and then consume message" in {
        val topic = "test-topic"
        val message = "Hello world"
        withRunningKafka{
          publishStringMessageToKafka(topic, message)
          consumeFirstStringMessageFrom(topic) shouldBe message
        }
      }
    }
  }
}
```
## dependency in pom
        <dependency>
            <groupId>net.manub</groupId>
            <artifactId>scalatest-embedded-kafka_2.11</artifactId>
            <version>0.10.0</version>
            <scope>test</scope>
        </dependency>

 @sameergarg

**Comment by manub** [comment]
`0.10.0` uses Kafka `0.10.1.0` under the hood, which version of Kafka are you using? This looks like a classpath issue to me and it shouldn't be related to Maven but more likely to transitive dependency. Does it work with `0.9.0`?

**Comment by sameergarg** [comment]
Yes, you are right. I was using an older version 0.8.2.2. Your code works perfectly with 0.10.1.0. Is there any jar compatible with 0.8.2.2?

I will close this issue now.

**Comment by manub** [comment]
Check version `v0.5.0-kafka08`
